/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Access = sequelize.define('Access', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    user_id: DataTypes.INTEGER(11),
    accessOn: DataTypes.DATE,
    ipv4: DataTypes.STRING(254),
    ipv6: DataTypes.STRING(254),
    platform: DataTypes.STRING(254),
    valid: DataTypes.BOOLEAN(1),
    revokedOn: DataTypes.DATE,
    city: DataTypes.STRING(254),
    country: DataTypes.STRING(254),
    accessToken: DataTypes.STRING(254),
  }, {
      tableName: 'Access',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Access.belongsTo(models.User, {
            foreignKey: 'user_id',              //on Access
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Access;
  };