/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Person = sequelize.define('Person', {
      email: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    firstName: DataTypes.STRING(254),
    lastName: DataTypes.STRING(254),
  }, {
      tableName: 'Person',
      timestamps: false,
      underscored: false,
     classMethods: {
        associate: function associate(models) {    
          Person.belongsTo(models.User, {
            foreignKey: 'id',              //on Person
            targetKey: 'person',  //foreign key  
          }); 
        }
      },
    });

    return Person;
  };