/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const User = sequelize.define('User', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    email: DataTypes.STRING(254),
    person: DataTypes.INTEGER(11),
    hash: DataTypes.STRING(254),
    createdOn: DataTypes.DATE,
    confirmationToken: DataTypes.STRING(254),
    active: DataTypes.BOOLEAN(1),
    attempt: DataTypes.INTEGER(5),
    ban: DataTypes.BOOLEAN(1),
  }, {
      tableName: 'User',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          User.belongsTo(models.Access, {
            foreignKey: 'id',              //on User
            targetKey: 'user_id',  //foreign key  
          });
          User.belongsTo(models.Person, {
            foreignKey: 'person',              //on User
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return User;
  };